//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessage
    {
        public int GroupMessageId { get; set; }
        public string GroupMessageName { get; set; }
        public string GroupMessageText { get; set; }
        public string GroupMessageColor { get; set; }
    }
}
