//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        public int PrivateMessageId { get; set; }
        public int PrivateMessageChatId { get; set; }
        public int PrivateMessageSenderId { get; set; }
        public string PrivateMessageName { get; set; }
        public string PrivateMessageText { get; set; }
        public string PrivateMessageColor { get; set; }
    }
}
